Repository Campus-Compass-SOEN-390/Watermelons_SOEN390, pull requests merged in 2025-02, with the labels that each got.

#98 F/map shapes imp
  myApp/app/utils/mapUtils.tsx
Labels: feature

#79 Create API Endpoint to Fetch Building Information and added unit tests for it
  jest.config.js
  myApp/app/__tests__/buildingService.test.ts
  myApp/app/api/buildingData.ts
  myApp/app/api/buildingService.ts
  myApp/jest.setup.js
  myApp/package-lock.json
  myApp/package.json
  myApp/yarn.lock
  package-lock.json
  package.json
  yarn.lock
Labels: backend

#111 Building info pop up
  myApp/app/(tabs)/outdoor-map.jsx
  myApp/app/LoyolaCampus.tsx
  myApp/app/SGWCampus.tsx
  myApp/app/__tests__/buildingData.test.tsx
  myApp/app/__tests__/buildingService.test.ts
  myApp/app/__tests__/mapUtils.test.tsx
  myApp/app/_layout.tsx
  myApp/app/api/buildingData.ts
  myApp/app/api/buildingService.ts
  myApp/app/components/BuildingPopUp.tsx
  myApp/app/components/LoyolaOutdoorMap.tsx
  myApp/app/components/OutdoorMapSwitcher.js
  myApp/app/hooks/useLocation.tsx
  myApp/app/styles/HomePageStyles.js
  myApp/app/styles/OutdoorMapStyles.js
  myApp/app/utils/mapUtils.tsx
  myApp/package-lock.json
  myApp/yarn.lock
Labels: feature

#126 Fetch Shuttle Schedule Data
  myApp/app/__tests__/shuttleApi.test.js
  myApp/app/api/shuttleLiveData.js
  myApp/app/api/shuttleSchedule.js
  myApp/app/api/shuttleScheduleData.js
  myApp/package-lock.json
  myApp/package.json
  myApp/tsconfig.json
  myApp/yarn.lock
Labels: backend, Sprint3

#154 build Shuttle Bus Schedule Button + fix terminal warnings
  myApp/app/__tests__/HomePage.tests.js
  myApp/app/api/shuttleLiveData.js
  myApp/app/api/shuttleSchedule.js
  myApp/app/api/shuttleScheduleData.js
  myApp/app/screens/HomePage.js
  myApp/app/screens/ShuttleScheduleScreen.js
  myApp/package-lock.json
  myApp/package.json
  myApp/yarn.lock
Labels: frontend
